// The tradesperson interface keeps Lithuanian as its source language. Only
// known interface copy is translated; names, user content and URLs are not.
export const russianCopy: Record<string, string> = {
  "Profilio santrauka": "Краткая информация о профиле",
  "Profilis aktyvus": "Профиль активен",
  "Profilis ruošiamas": "Профиль готовится",
  "Profilis paslėptas": "Профиль скрыт",
  "Profilis sustabdytas": "Профиль приостановлен",
  "Laukia patvirtinimo": "Ожидает подтверждения",
  "Reikia pataisyti": "Требуется исправление",
  "Užklausos": "Заявки",
  "Mano profilis": "Мой профиль",
  "Profilis": "Профиль",
  "Nuotraukos": "Фотографии",
  "Paslaugos": "Услуги",
  "Paskyra": "Аккаунт",
  "Atsijungti": "Выйти",
  "Mobilioji navigacija": "Мобильная навигация",
  "Meistro paskyra": "Аккаунт специалиста",
  "Pranešimai": "Уведомления",
  "Paskyros ištrynimas suplanuotas. Profilis paslėptas, o pakeitimai išjungti. Ištrynimą galite atšaukti paskyros puslapyje.": "Удаление аккаунта запланировано. Профиль скрыт, изменения отключены. Отменить удаление можно на странице аккаунта.",
  "Paskyros ištrynimas suplanuotas": "Удаление аккаунта запланировано",
  "Kol ištrynimas neatšauktas, šios paskyros duomenų keisti negalima.": "Пока удаление не отменено, данные аккаунта нельзя изменить.",
  "Atidaryti paskyrą": "Открыть аккаунт",
  "Užbaikite registraciją": "Завершите регистрацию",
  "Sukurkite savo LocalPro specialisto profilį.": "Создайте профиль специалиста LocalPro.",
  "Profilis bus saugiai susietas su šia paskyra ir taps aktyvus, kai užpildysite privalomus laukus.": "Профиль будет надёжно привязан к этому аккаунту и станет активным после заполнения обязательных полей.",
  "Tęsti registraciją": "Продолжить регистрацию",
  "Naujos": "Новые",
  "Peržiūrėtos": "Просмотренные",
  "Susisiekta": "Связались",
  "Domina": "Интересует",
  "Atmestos": "Отклонённые",
  "Archyvas": "Архив",
  "naujos": "новые",
  "peržiūrėtos": "просмотренные",
  "susisiekta": "связались",
  "Laukia peržiūros": "Ожидают просмотра",
  "Per pastarąsias 30 d.": "За последние 30 дней",
  "Profilio užpildymas": "Заполнение профиля",
  "Puiku!": "Отлично!",
  "Užbaikite profilį": "Завершите профиль",
  "Užklausų statistika": "Статистика заявок",
  "Užklausų filtrai": "Фильтры заявок",
  "Užklausų sąrašas": "Список заявок",
  "Kraunamos užklausos…": "Загрузка заявок…",
  "Bandyti dar kartą": "Повторить попытку",
  "Nauja": "Новая",
  "Peržiūrėta": "Просмотрена",
  "Priimta": "Принята",
  "Atmesta": "Отклонена",
  "Atitinka paslaugas": "Соответствует услугам",
  "Neatitinka paslaugų": "Не соответствует услугам",
  "Darbo zonoje": "В зоне работы",
  "Už darbo zonos": "Вне зоны работы",
  "Šiame aplanke užklausų nėra.": "В этой папке нет заявок.",
  "Uždaryti": "Закрыть",
  "Paslauga": "Услуга",
  "Pageidaujamas laikas": "Желаемое время",
  "Vieta": "Место",
  "apytikslė vietovė": "приблизительное местоположение",
  "Kliento darbų nuotrauka": "Фото работы клиента",
  "Skambinti": "Позвонить",
  "El. paštas": "Эл. почта",
  "Kontaktai parodomi tik sąmoningai pasirinkus „Domina“ arba „Susisiekti“.": "Контакты открываются только после выбора «Интересует» или «Связаться».",
  "Susisiekti": "Связаться",
  "Nedomina": "Не интересует",
  "Archyvuoti": "В архив",
  "Tvarkyti": "Изменить",
  "Pasirinktos paslaugos": "Выбранные услуги",
  "Paslaugų dar nepasirinkta.": "Услуги пока не выбраны.",
  "Rodyti visas paslaugas": "Показать все услуги",
  "Lankstus": "Гибко",
  "Per savaitę": "В течение недели",
  "Skubu": "Срочно",
  "Būsena atnaujinta.": "Статус обновлён.",
  "Užklausų įkelti nepavyko.": "Не удалось загрузить заявки.",
  "Atnaujinti nepavyko.": "Не удалось обновить.",
  "Saugoma...": "Сохранение...",
  "Peržiūrėti viešą profilį": "Посмотреть публичный профиль",
  "Atidaryti viešą profilį": "Открыть публичный профиль",
  "Atidaryti Nuotraukas ir bandyti dar kartą": "Открыть фотографии и повторить попытку",
  "Mano paslaugos": "Мои услуги",
  "Pasirinkite darbo sritis ir konkrečias paslaugas, privačią darbo bazę bei vieną bendrą aptarnavimo spindulį.": "Выберите направления и услуги, личный рабочий адрес и единый радиус обслуживания.",
  "Darbo sritys ir paslaugos": "Направления и услуги",
  "Darbo sritys": "Направления",
  "Ieškoti paslaugos": "Поиск услуги",
  "Darbo vieta ir spindulys": "Рабочий адрес и радиус",
  "Pagrindinis miestas": "Основной город",
  "Privatus darbo bazės adresas": "Личный рабочий адрес",
  "Tikslus adresas ir koordinatės yra privatūs. Klientai mato tik bendrą vietovę ir aptarnavimo zoną.": "Точный адрес и координаты конфиденциальны. Клиенты видят только общий район и зону обслуживания.",
  "Vienas paslaugų spindulys": "Радиус обслуживания",
  "Visa Lietuva": "Вся Литва",
  "Išsaugoti paslaugas": "Сохранить услуги",
  "Pasirinkite bent vieną darbo sritį prieš išsaugodami.": "Выберите хотя бы одно направление перед сохранением.",
  "Ankstesnės darbo srities nepavyko saugiai priskirti. Pasirinkite tinkamą darbo sritį prieš išsaugodami.": "Не удалось сопоставить прежнее направление. Выберите подходящее направление перед сохранением.",
  "Pasiekėte 25 paslaugų limitą.": "Достигнут лимит в 25 услуг.",
  "Profilio informacija": "Информация о профиле",
  "Tvarkykite viešą profilį ir kontaktinius duomenis. Prisijungimo el. paštas keičiamas tik skiltyje „Paskyra“.": "Управляйте публичным профилем и контактами. Адрес почты для входа меняется только в разделе «Аккаунт».",
  "Jūsų profilis matomas meistrų žemėlapyje.": "Ваш профиль виден на карте специалистов.",
  "Jūsų profilis laikinai nerodomas žemėlapyje ir paieškoje.": "Ваш профиль временно скрыт с карты и из поиска.",
  "Užbaikite trūkstamus profilio punktus.": "Заполните недостающие разделы профиля.",
  "Laikinai paslėpti profilį": "Временно скрыть профиль",
  "Vėl rodyti profilį": "Снова показывать профиль",
  "Profilis laikinai paslėptas.": "Профиль временно скрыт.",
  "Profilis vėl rodomas viešai.": "Профиль снова виден всем.",
  "Profilio matomumo pakeisti nepavyko.": "Не удалось изменить видимость профиля.",
  "Profilio matomumo pakeisti nepavyko. Bandykite dar kartą.": "Не удалось изменить видимость профиля. Повторите попытку.",
  "Pagrindinė informacija": "Основная информация",
  "Vardas ir pavardė": "Имя и фамилия",
  "Įmonės arba veiklos pavadinimas": "Название компании или деятельности",
  "Pagrindinė specialybė": "Основная специальность",
  "Pasirinkite specialybę": "Выберите специальность",
  "Anksčiau išsaugotos specialybės nepavyko susieti su dabartiniu sąrašu. Pasirinkite ją iš naujo.": "Ранее сохранённая специальность не найдена в текущем списке. Выберите её снова.",
  "Patirties metai": "Лет опыта",
  "Trumpas aprašymas": "Краткое описание",
  "Kainodara": "Цены",
  "Nurodykite orientacinę darbo kainą. Medžiagos neįskaičiuotos. Galutinė kaina gali priklausyti nuo darbų kiekio, sudėtingumo ir objekto būklės.": "Укажите ориентировочную стоимость работы без материалов. Итоговая цена зависит от объёма, сложности и состояния объекта.",
  "Valandinis įkainis": "Почасовая ставка",
  "Kaina už m²": "Цена за м²",
  "Sutartinė / už visą darbą": "По договорённости / за всю работу",
  "Pašalinti": "Удалить",
  "Pridėti paslaugos m² kainą": "Добавить цену за м² для услуги",
  "Pasirinkite paslaugą": "Выберите услугу",
  "Kontaktai": "Контакты",
  "Viešas telefono numeris": "Публичный номер телефона",
  "WhatsApp numeris": "Номер WhatsApp",
  "Viešas kontaktinis el. paštas": "Публичная контактная почта",
  "Tai nėra „Google“ prisijungimo el. paštas.": "Это не адрес почты для входа через Google.",
  "Kalbos (nebūtina)": "Языки (необязательно)",
  "Lietuvių, anglų, lenkų": "Литовский, английский, польский",
  "Atskirkite kableliais.": "Разделяйте запятыми.",
  "Sutinku, kad viešame profilyje būtų rodomi mano pasirinkti kontaktiniai duomenys.": "Согласен на показ выбранных контактных данных в публичном профиле.",
  "Išsaugoti pakeitimus": "Сохранить изменения",
  "Profilis išsaugotas.": "Профиль сохранён.",
  "Išsaugoti nepavyko.": "Не удалось сохранить.",
  "Nuotraukų filtrai": "Фильтры фотографий",
  "Darbų nuotraukos": "Фотографии работ",
  "Jūsų darbų galerija": "Галерея ваших работ",
  "Visos": "Все",
  "Patvirtintos": "Подтверждённые",
  "Laukia": "Ожидают",
  "Tikrinama": "Проверяется",
  "Pagrindinė": "Основная",
  "Patvirtinta": "Подтверждена",
  "Priežastis": "Причина",
  "Pakeisti": "Заменить",
  "Pasirinkti nuotraukas": "Выбрать фотографии",
  "Įkeliama...": "Загрузка...",
  "Įkeliama…": "Загрузка…",
  "Išsaugota.": "Сохранено.",
  "Veiksmas nepavyko.": "Не удалось выполнить действие.",
  "Nuotraukos paskelbtos.": "Фотографии опубликованы.",
  "Nuotraukos optimizuojamos…": "Оптимизация фотографий…",
  "Naujos ir pakeistos nuotraukos paskelbiamos iškart. Netinkamą turinį administratorius gali pašalinti po paskelbimo.": "Новые и заменённые фотографии публикуются сразу. Администратор может удалить неподходящий контент после публикации.",
  "Prisijungimas, nuosavybė, privatumas ir pagalba.": "Вход, владение профилем, конфиденциальность и помощь.",
  "Prisijungimo duomenys": "Данные для входа",
  "Google paskyros el. paštas": "Почта аккаунта Google",
  "Nenurodytas": "Не указан",
  "Patvirtinimas": "Подтверждение",
  "El. paštas patvirtintas": "Почта подтверждена",
  "Prisijungimo būdas": "Способ входа",
  "Google paskyra neprijungta": "Аккаунт Google не подключён",
  "Profilio nuosavybė": "Владение профилем",
  "Paskyra saugiai susieta su specialisto profiliu.": "Аккаунт надёжно привязан к профилю специалиста.",
  "Ši paskyra dar nesusieta su specialisto profiliu.": "Этот аккаунт ещё не привязан к профилю специалиста.",
  "Susieti profilį": "Привязать профиль",
  "Privatumas ir paskyros veiksmai": "Конфиденциальность и действия с аккаунтом",
  "Viešas kontaktinis el. paštas keičiamas skiltyje „Mano profilis“ ir nėra naudojamas prisijungimo nuosavybei nustatyti.": "Публичная контактная почта меняется в разделе «Мой профиль» и не используется для подтверждения владения аккаунтом.",
  "Privatumo politika": "Политика конфиденциальности",
  "Naudojimo sąlygos": "Условия использования",
  "Administravimas": "Администрирование",
  "Šiai paskyrai serveris patvirtino administratoriaus prieigą.": "Для этого аккаунта подтверждены права администратора.",
  "Atidaryti administravimą": "Открыть администрирование",
  "Prašyti savo duomenų kopijos": "Запросить копию своих данных",
  "Visam laikui ištrinti paskyrą": "Удалить аккаунт навсегда",
  "Jūsų profilis paslėptas.": "Ваш профиль скрыт.",
  "Ištrynimo vykdymas laikinai nepavyko. Profilis lieka paslėptas, o sistema bandys dar kartą.": "Удаление временно не удалось. Профиль остаётся скрытым, система повторит попытку.",
  "Atšaukti paskyros ištrynimą": "Отменить удаление аккаунта",
  "Jūsų profilis bus iš karto paslėptas. Po 7 dienų paskyra, kontaktiniai duomenys, paslaugos ir darbų nuotraukos bus visam laikui ištrinti. Iki tol galėsite ištrynimą atšaukti.": "Ваш профиль будет скрыт сразу. Через 7 дней аккаунт, контакты, услуги и фотографии работ будут удалены навсегда. До этого момента удаление можно отменить.",
  "Ištrinti paskyrą": "Удалить аккаунт",
  "Patvirtinti paskyros ištrynimą": "Подтвердить удаление аккаунта",
  "Patvirtinimui įveskite dabartinį prisijungimo el. paštą.": "Для подтверждения введите текущий адрес почты для входа.",
  "Prisijungimo el. paštas": "Почта для входа",
  "Suprantu, kad po 7 dienų paskyros ištrynimas bus negrįžtamas.": "Я понимаю, что через 7 дней удаление аккаунта станет необратимым.",
  "Grįžti": "Назад",
  "Susisiekti su pagalba": "Связаться с поддержкой",
  "serverio nustatytą dieną": "в дату, назначенную сервером",
  "Rasta paskyra": "Аккаунт найден",
  "Galite atidaryti savo LocalPro paskyrą.": "Вы можете открыть свой аккаунт LocalPro.",
  "Patvirtinus paskyra bus saugiai susieta su jūsų patvirtintu prisijungimu.": "После подтверждения аккаунт будет надёжно привязан к вашему подтверждённому входу.",
  "Reikia administratoriaus sprendimo": "Требуется решение администратора",
  "Paskyros automatiškai susieti negalime.": "Не удалось автоматически привязать аккаунт.",
  "Automatinis susiejimas sustabdytas, kad paskyra nebūtų perduota netinkamam asmeniui. Norėdami pradėti rankinę peržiūrą, parašykite pagalbai iš savo patvirtinto el. pašto ir trumpai nurodykite profilio pavadinimą.": "Автоматическая привязка остановлена, чтобы аккаунт не попал другому человеку. Для ручной проверки напишите в поддержку с подтверждённой почты и укажите название профиля.",
  "Kreiptis dėl nuosavybės patikros": "Запросить проверку владения",
  "Grįžti į pradžią": "На главную",
  "Paskyra susiejama...": "Привязка аккаунта...",
  "Paskyros susieti nepavyko.": "Не удалось привязать аккаунт.",
  "Paskyros susieti nepavyko. Patikrinkite ryšį ir bandykite dar kartą.": "Не удалось привязать аккаунт. Проверьте соединение и повторите попытку.",
  "LocalPro paskyra": "Аккаунт LocalPro",
  "Prisijunkite arba registruokitės": "Войдите или зарегистрируйтесь",
  "Po pirmo prisijungimo užpildysite trumpą registraciją. LocalPro sukurs naują specialisto profilį ir saugiai susies jį su jūsų paskyra.": "После первого входа заполните короткую регистрацию. LocalPro создаст профиль специалиста и надёжно привяжет его к вашему аккаунту.",
  "Tęsti su Google": "Продолжить через Google",
  "Prisijungti nepavyko.": "Не удалось войти.",
  "Nepavyko pradėti „Google“ prisijungimo.": "Не удалось начать вход через Google.",
  "Nepavyko patvirtinti prisijungimo.": "Не удалось подтвердить вход.",
  "Prisijungimas laikinai nesukonfigūruotas.": "Вход временно не настроен.",
  "Grįžti į pagrindinį puslapį": "Вернуться на главную",
  "Meistro registracija": "Регистрация специалиста",
  "Specialisto registracija": "Регистрация специалиста",
  "Registruotis": "Зарегистрироваться",
  "Toliau": "Далее",
  "Atgal": "Назад"
};

Object.assign(russianCopy, {
  "Specialistams": "Специалистам",
  "Prisijunkite, užpildykite privalomus profilio laukus ir pradėkite naudotis savo meistro paskyra. Nuotraukas galėsite papildyti ir vėliau.": "Войдите, заполните обязательные поля профиля и начните пользоваться аккаунтом специалиста. Фотографии можно добавить позже.",
  "Paskyros patvirtinimas": "Подтверждение аккаунта",
  "Prisijunkite arba sukurkite paskyrą": "Войдите или создайте аккаунт",
  "Po prisijungimo grįšite į šį puslapį ir galėsite užpildyti meistro registraciją.": "После входа вы вернётесь на эту страницу и сможете заполнить регистрацию специалиста.",
  "Administratoriaus paskyra": "Аккаунт администратора",
  "Meistro profilis nebus sukurtas automatiškai": "Профиль специалиста не будет создан автоматически",
  "Jeigu taip pat teikiate meistro paslaugas, registraciją galite pradėti sąmoningai.": "Если вы также оказываете услуги специалиста, вы можете начать регистрацию вручную.",
  "Registruotis kaip meistrui": "Зарегистрироваться как специалист",
  "Registracija gauta": "Регистрация получена",
  "Profilis aktyvus.": "Профиль активен.",
  "Profilis iškart matomas viešai. Tinkamos įkeltos nuotraukos taip pat paskelbiamos iškart ir gali būti peržiūrėtos administratoriaus.": "Профиль сразу виден всем. Подходящие фотографии также публикуются сразу и могут быть проверены администратором.",
  "Adresas gautas kaip įrašytas ranka. Prieš publikavimą jį peržiūrėsime ir prireikus patikslinsime.": "Адрес введён вручную. Перед публикацией мы проверим и при необходимости уточним его.",
  "Grįžti į žemėlapį": "Вернуться к карте",
  "LocalPro specialisto registracijos forma": "Форма регистрации специалиста LocalPro",
  "Vardas arba įmonės pavadinimas *": "Имя или название компании *",
  "Telefono numeris *": "Номер телефона *",
  "Viešas kontaktinis el. paštas *": "Публичная контактная почта *",
  "Automatiškai užpildytą Google paskyros adresą galite pakeisti kitu klientams skirtu kontaktiniu adresu.": "Автоматически подставленный адрес Google можно заменить другим контактным адресом для клиентов.",
  "Registracijos adresas": "Адрес регистрации",
  "Pvz. Trakų g. 10, Lentvaris": "Например: ул. Траку, 10, Лентварис",
  "Klientams rodoma tik bendra vietovė ir aptarnavimo zona.": "Клиенты видят только общий район и зону обслуживания.",
  "Pasirinkite bent 2 paslaugas. Ta pati paslauga, rodoma keliose darbo srityse, skaičiuojama tik vieną kartą. Jei paslaugos sąraše nėra, įrašykite ją aprašyme.": "Выберите не менее двух услуг. Одна и та же услуга в нескольких направлениях учитывается один раз. Если нужной услуги нет в списке, укажите её в описании.",
  "Kaip dažniausiai skaičiuojate savo darbą? *": "Как вы обычно оцениваете свою работу? *",
  "Darbo kaina": "Стоимость работы",
  "Leidžiama nuo 10 € iki 100 €": "Допустимо от 10 € до 100 €",
  "Kainą sutarsite su klientu įvertinę visą darbą.": "Вы согласуете цену с клиентом после оценки всей работы.",
  "Darbų nuotraukos nebūtinos": "Фотографии работ необязательны",
  "Galite pridėti iki 8 darbų nuotraukų dabar arba papildyti profilį vėliau.": "Сейчас можно добавить до 8 фотографий работ или дополнить профиль позже.",
  "Pridėti daugiau nuotraukų": "Добавить ещё фотографии",
  "Pridėti nuotraukas": "Добавить фотографии",
  "Pasirinkite failus iš telefono arba kompiuterio": "Выберите файлы с телефона или компьютера",
  "Pasirinktos nuotraukos": "Выбранные фотографии",
  "Peržiūra nepasiekiama": "Предпросмотр недоступен",
  "Išplėstiniai nustatymai: nuotraukų URL": "Расширенные настройки: URL фотографий",
  "Pridėti URL": "Добавить URL",
  "Kokiu atstumu vykstate į darbus? *": "Как далеко вы выезжаете на работу? *",
  "Darbo zona skaičiuojama kaip spindulys aplink pagrindinę darbo vietą.": "Рабочая зона определяется радиусом вокруг основного рабочего адреса.",
  "Sutinku su LocalPro": "Я согласен с LocalPro",
  "naudojimosi sąlygomis": "условиями использования",
  "ir susipažinau su": "и ознакомился с",
  "privatumo politika": "политикой конфиденциальности",
  "Sutinku, kad aktyviame profilyje viešai būtų rodomi mano pasirinkti kontaktai.": "Я согласен на публичный показ выбранных контактов в активном профиле.",
  "Registruojama...": "Регистрация...",
  "Užbaigti registraciją": "Завершить регистрацию",
  "Ieškoma...": "Поиск...",
  "Adreso paieška laikinai neveikia. Galite adresą įrašyti ranka.": "Поиск адреса временно недоступен. Можно ввести адрес вручную.",
  "Adreso pasirinkti nepavyko. Galite adresą palikti įrašytą ranka.": "Не удалось выбрать адрес. Можно оставить адрес, введённый вручную.",
  "Įveskite vardą arba įmonės pavadinimą.": "Введите имя или название компании.",
  "Įveskite lietuvišką numerį, pvz. 063601230 arba +37063601230.": "Введите литовский номер, например 063601230 или +37063601230.",
  "Įveskite galiojantį el. pašto adresą.": "Введите действительный адрес электронной почты.",
  "Įveskite registracijos adresą arba vietovę Lietuvoje.": "Введите адрес регистрации или населённый пункт в Литве.",
  "Pasirinkite bent vieną darbo sritį.": "Выберите хотя бы одно направление работы.",
  "Pasirinkite bent 2 konkrečias paslaugas.": "Выберите как минимум две конкретные услуги.",
  "Aprašymas turi būti bent 80 simbolių.": "Описание должно содержать не менее 80 символов.",
  "Pridėkite galiojančias, nesikartojančias pasirinktų paslaugų m² kainas.": "Добавьте корректные цены за м² для выбранных услуг без повторов.",
  "Sutikite su sąlygomis ir patvirtinkite, kad susipažinote su privatumo politika.": "Примите условия и подтвердите ознакомление с политикой конфиденциальности.",
  "Patvirtinkite viešų kontaktų rodymo sutikimą.": "Подтвердите согласие на показ публичных контактов.",
  "Prisijungti": "Войти",
  "Meniu": "Меню",
  "Prisijungta kaip": "Вошли как",
  "Prisijungusio naudotojo paskyra": "Аккаунт пользователя",
  "Puslapio skyriai": "Разделы страницы",
  "Mobiliojo puslapio skyriai": "Мобильные разделы страницы"
});

// Active LocalPro trade taxonomy, translated for selecting and reviewing work.
Object.assign(russianCopy, {
  "Vidaus apdaila": "Внутренняя отделка",
  "Santechnika": "Сантехника",
  "Elektra ir apsaugos sistemos": "Электрика и системы безопасности",
  "Šildymas, vėdinimas ir kondicionavimas": "Отопление, вентиляция и кондиционирование",
  "Stogai ir skardinimas": "Кровля и жестяные работы",
  "Fasadai ir šiltinimas": "Фасады и утепление",
  "Statyba ir konstrukcijos": "Строительство и конструкции",
  "Langai, durys ir laiptai": "Окна, двери и лестницы",
  "Medžio darbai ir baldai": "Столярные работы и мебель",
  "Lauko ir sklypo darbai": "Работы на участке",
  "Griovimas ir atliekų išvežimas": "Демонтаж и вывоз отходов",
  "Meistras į namus": "Мастер на дом",
  "Projektavimas ir darbų priežiūra": "Проектирование и надзор за работами",
  "Plytelių klijavimas": "Укладка плитки",
  "Vonios kambario įrengimas": "Обустройство ванной комнаты",
  "Glaistymas": "Шпатлёвка",
  "Dažymas": "Покраска",
  "Tapetavimas": "Поклейка обоев",
  "Gipso kartono montavimas": "Монтаж гипсокартона",
  "Pertvarų montavimas": "Монтаж перегородок",
  "Pakabinamų lubų montavimas": "Монтаж подвесных потолков",
  "Laminato klojimas": "Укладка ламината",
  "Parketo ir medinių grindų darbai": "Паркет и деревянные полы",
  "Grindjuosčių montavimas": "Монтаж плинтусов",
  "Vidaus durų montavimas": "Монтаж межкомнатных дверей",
  "Pilna buto apdaila": "Полная отделка квартиры",
  "Pilna būsto apdaila ir remontas": "Полная отделка и ремонт жилья",
  "Gipso kartono ir pertvarų montavimas": "Монтаж гипсокартона и перегородок",
  "Remonto darbai": "Ремонтные работы",
  "Vandentiekio vamzdynai": "Водопроводные трубы",
  "Nuotekų vamzdynai": "Канализационные трубы",
  "Santechnikos remontas": "Ремонт сантехники",
  "Unitazų montavimas": "Установка унитазов",
  "Praustuvų montavimas": "Установка раковин",
  "Maišytuvų montavimas": "Установка смесителей",
  "Vonių montavimas": "Установка ванн",
  "Dušo kabinų montavimas": "Установка душевых кабин",
  "Boilerio montavimas": "Установка бойлера",
  "Vandens filtrų montavimas": "Установка фильтров воды",
  "Trapų ir nuotekų pajungimas": "Подключение трапов и канализации",
  "Avarinė santechnika": "Аварийные сантехнические работы",
  "Elektros instaliacija": "Электропроводка",
  "Elektros instaliacijos remontas": "Ремонт электропроводки",
  "Rozečių montavimas": "Установка розеток",
  "Rozečių ir jungiklių montavimas": "Установка розеток и выключателей",
  "Jungiklių montavimas": "Установка выключателей",
  "Šviestuvų montavimas": "Установка светильников",
  "Elektros skydelio darbai": "Работы с электрощитом",
  "Gedimų paieška": "Поиск неисправностей",
  "Lauko apšvietimas": "Наружное освещение",
  "Signalizacijos": "Сигнализации",
  "Vaizdo stebėjimo kameros": "Камеры видеонаблюдения",
  "Domofonai": "Домофоны",
  "Elektromobilių įkrovimo stotelės": "Зарядные станции для электромобилей",
  "Katilų montavimas": "Установка котлов",
  "Katilų remontas": "Ремонт котлов",
  "Šilumos siurblių montavimas": "Установка тепловых насосов",
  "Grindinis šildymas": "Тёплый пол",
  "Radiatorių montavimas": "Установка радиаторов",
  "Rekuperacijos sistemos": "Системы рекуперации",
  "Vėdinimo ir rekuperacijos sistemos": "Системы вентиляции и рекуперации",
  "Vėdinimo sistemos": "Системы вентиляции",
  "Kondicionierių montavimas": "Установка кондиционеров",
  "Kondicionierių priežiūra": "Обслуживание кондиционеров",
  "Kaminų montavimas": "Монтаж дымоходов",
  "Kaminų valymas": "Чистка дымоходов",
  "Naujo stogo įrengimas": "Монтаж новой кровли",
  "Stogo įrengimas ir dangos keitimas": "Монтаж кровли и замена покрытия",
  "Stogo remontas": "Ремонт кровли",
  "Stogo šiltinimas": "Утепление кровли",
  "Stogo dangos keitimas": "Замена кровельного покрытия",
  "Skardinimo darbai": "Жестяные работы",
  "Lietaus nuvedimo sistemos": "Водосточные системы",
  "Stogo latakai ir lietvamzdžiai": "Водосточные желоба и трубы",
  "Kaminų skardinimas": "Обшивка дымоходов металлом",
  "Stoglangių montavimas": "Установка мансардных окон",
  "Sniego užtvarų montavimas": "Монтаж снегозадержателей",
  "Fasado šiltinimas": "Утепление фасада",
  "Fasado tinkavimas": "Штукатурка фасада",
  "Fasado dažymas": "Покраска фасада",
  "Ventiliuojami fasadai": "Вентилируемые фасады",
  "Cokolio apdaila": "Отделка цоколя",
  "Angokraščių apdaila": "Отделка откосов",
  "Lauko sienų remontas": "Ремонт наружных стен",
  "Pastatų sandarinimas": "Герметизация зданий",
  "Individualių namų statyba": "Строительство частных домов",
  "Karkasinių namų statyba": "Строительство каркасных домов",
  "Mūro darbai": "Кладочные работы",
  "Pamatų įrengimas": "Устройство фундамента",
  "Betonavimas": "Бетонные работы",
  "Perdangų įrengimas": "Монтаж перекрытий",
  "Priestatų statyba": "Строительство пристроек",
  "Stoginių statyba": "Строительство навесов",
  "Stoginės, pergolės ir pavėsinės": "Навесы, перголы и беседки",
  "Angų įrengimas": "Устройство проёмов",
  "Angų pjovimas ir įrengimas": "Резка и устройство проёмов",
  "Metalo konstrukcijos": "Металлоконструкции",
  "Langų montavimas": "Установка окон",
  "Langų remontas ir reguliavimas": "Ремонт и регулировка окон",
  "Lauko durų montavimas": "Установка входных дверей",
  "Garažo vartai": "Гаражные ворота",
  "Laiptų gamyba": "Изготовление лестниц",
  "Laiptų gamyba ir montavimas": "Изготовление и установка лестниц",
  "Laiptų montavimas": "Установка лестниц",
  "Turėklai": "Перила",
  "Stiklo konstrukcijos": "Стеклянные конструкции",
  "Virtuvės baldų gamyba": "Изготовление кухонной мебели",
  "Spintų gamyba": "Изготовление шкафов",
  "Individualių baldų gamyba": "Изготовление мебели на заказ",
  "Baldų surinkimas": "Сборка мебели",
  "Baldų remontas": "Ремонт мебели",
  "Staliaus darbai": "Столярные работы",
  "Medinių terasų įrengimas": "Строительство деревянных террас",
  "Pergolės": "Перголы",
  "Pavėsinės": "Беседки",
  "Mediniai nameliai": "Деревянные домики",
  "Trinkelių klojimas": "Укладка брусчатки",
  "Tvorų montavimas": "Установка заборов",
  "Tvorų ir vartų montavimas": "Установка заборов и ворот",
  "Vartų montavimas": "Установка ворот",
  "Žemės kasimas": "Земляные работы",
  "Sklypo lyginimas": "Выравнивание участка",
  "Drenažas": "Дренаж",
  "Lietaus nuotekos": "Ливневая канализация",
  "Lietaus nuotekų tinklai sklype": "Ливневая канализация на участке",
  "Apželdinimas": "Озеленение",
  "Vejos įrengimas": "Устройство газона",
  "Vejos priežiūra": "Уход за газоном",
  "Medžių genėjimas": "Обрезка деревьев",
  "Kelmų šalinimas": "Удаление пней",
  "Griovimo darbai": "Демонтажные работы",
  "Pastatų ir konstrukcijų griovimas": "Снос зданий и конструкций",
  "Sienų ardymas": "Демонтаж стен",
  "Sienų ir pertvarų ardymas": "Демонтаж стен и перегородок",
  "Pertvarų ardymas": "Демонтаж перегородок",
  "Plytelių ardymas": "Демонтаж плитки",
  "Grindų ardymas": "Демонтаж полов",
  "Angų pjovimas": "Резка проёмов",
  "Deimantinis gręžimas": "Алмазное бурение",
  "Statybinių atliekų išvežimas": "Вывоз строительного мусора",
  "Objekto paruošimas remontui": "Подготовка объекта к ремонту",
  "Smulkūs remonto darbai": "Мелкий ремонт",
  "Lentynų montavimas": "Установка полок",
  "Televizoriaus tvirtinimas": "Крепление телевизора",
  "Karnizų montavimas": "Установка карнизов",
  "Silikonavimas": "Герметизация силиконом",
  "Spynų keitimas": "Замена замков",
  "Spynų ir durų furnitūros keitimas": "Замена замков и дверной фурнитуры",
  "Durų rankenų keitimas": "Замена дверных ручек",
  "Smulkūs santechnikos darbai": "Мелкие сантехнические работы",
  "Santechnikos remontas ir smulkūs darbai": "Ремонт сантехники и мелкие работы",
  "Smulkūs elektros darbai": "Мелкие электромонтажные работы",
  "Elektros remontas ir smulkūs darbai": "Ремонт электрики и мелкие работы",
  "Architektūros projektavimas": "Архитектурное проектирование",
  "Interjero dizainas": "Дизайн интерьера",
  "Konstrukcijų projektavimas": "Проектирование конструкций",
  "Inžinerinių sistemų projektavimas": "Проектирование инженерных систем",
  "Sąmatų sudarymas": "Составление смет",
  "Statybos darbų vadovas": "Руководитель строительных работ",
  "Techninė priežiūra": "Технический надзор",
  "Statybos dokumentų tvarkymas": "Оформление строительной документации"
});

Object.assign(russianCopy, {
  "Adresų nerasta": "Адреса не найдены",
  "Paslaugos ir darbo zona išsaugotos.": "Услуги и зона работы сохранены.",
  "Nuotraukų eilė tuščia.": "Очередь фотографий пуста.",
  "1 nuotrauka optimizuota ir paruošta peržiūrai.": "Одна фотография обработана и готова к просмотру.",
  "Serveris neparuošė nuotraukos įkėlimo.": "Сервер не подготовил загрузку фотографии.",
  "Nuotraukos įkelti nepavyko.": "Не удалось загрузить фотографию.",
  "Neleistina užklausa.": "Недопустимый запрос.",
  "Profilis nesusietas.": "Профиль не привязан.",
  "Duomenų bazė nepasiekiama.": "База данных недоступна.",
  "Paskyros ištrynimas suplanuotas. Pakeitimai laikinai išjungti.": "Удаление аккаунта запланировано. Изменения временно отключены.",
  "Paskyros ištrynimas suplanuotas. Nuotraukų keisti negalima.": "Удаление аккаунта запланировано. Фотографии нельзя изменить.",
  "Paskyros ištrynimas suplanuotas. Profilio viešinti negalima.": "Удаление аккаунта запланировано. Профиль нельзя сделать публичным.",
  "Patikrinkite darbo sritis, paslaugas ir darbo zoną.": "Проверьте направления, услуги и зону работы.",
  "Paslaugų ir darbo zonos išsaugoti nepavyko.": "Не удалось сохранить услуги и зону работы.",
  "Patikrinkite įvestus duomenis.": "Проверьте введённые данные.",
  "Profilio išsaugoti nepavyko.": "Не удалось сохранить профиль.",
  "Paslaugų kainų išsaugoti nepavyko.": "Не удалось сохранить цены услуг.",
  "m² kainos gali būti susietos tik su pasirinktomis paslaugomis.": "Цены за м² можно указать только для выбранных услуг.",
  "Neteisingas matomumo pasirinkimas.": "Неверно выбрана видимость.",
  "Profilį vėl rodyti galima tik tada, kai jis patvirtintas.": "Профиль можно снова показывать только после подтверждения.",
  "Prieš vėl rodydami profilį užbaikite privalomus profilio duomenis.": "Прежде чем снова показывать профиль, заполните обязательные данные.",
  "Profilio būsena pasikeitė. Atnaujinkite puslapį ir bandykite dar kartą.": "Статус профиля изменился. Обновите страницу и повторите попытку.",
  "Užklausų gauti nepavyko.": "Не удалось получить заявки.",
  "Užklausa nerasta.": "Заявка не найдена.",
  "Netinkamas veiksmas.": "Недопустимое действие.",
  "Būsenos pakeisti nepavyko.": "Не удалось изменить статус.",
  "Saugykla nepasiekiama.": "Хранилище недоступно.",
  "Galerijos nuotrauka turi būti iki 1 MB, o kortelės versija – iki 150 KB.": "Фото галереи должно быть не больше 1 МБ, а версия для карточки — не больше 150 КБ.",
  "Keičiama nuotrauka nerasta.": "Заменяемая фотография не найдена.",
  "Galima turėti daugiausia 8 nuotraukas.": "Можно иметь не более 8 фотографий.",
  "Nepavyko paruošti įkėlimo.": "Не удалось подготовить загрузку.",
  "Įkėlimo leidimas negalioja.": "Разрешение на загрузку недействительно.",
  "Nežinomas veiksmas.": "Неизвестное действие.",
  "Įkelti failai neatitiko reikalavimų.": "Загруженные файлы не соответствуют требованиям.",
  "Nuotraukos įrašyti nepavyko.": "Не удалось сохранить фотографию.",
  "Kortelės nuotraukos įrašyti nepavyko.": "Не удалось сохранить фото карточки.",
  "Nuotraukos paskelbti nepavyko.": "Не удалось опубликовать фотографию.",
  "Nuotrauka nerasta.": "Фотография не найдена.",
  "Pagrindinė gali būti tik patvirtinta nuotrauka.": "Основной может быть только подтверждённая фотография.",
  "Neteisingas prašymas.": "Неверный запрос.",
  "Paslauga nepasiekiama.": "Сервис недоступен.",
  "Toks prašymas jau laukia vykdymo.": "Такой запрос уже ожидает выполнения.",
  "Duomenų kopijos prašymas užregistruotas.": "Запрос копии данных зарегистрирован.",
  "Įvestas el. paštas nesutampa su prisijungimo el. paštu.": "Указанная почта не совпадает с почтой для входа.",
  "Serveris negrąžino ištrynimo datos.": "Сервер не вернул дату удаления.",
  "Paskyros ištrynimas suplanuotas.": "Удаление аккаунта запланировано.",
  "Ištrynimas jau pradėtas ir jo atšaukti nebegalima.": "Удаление уже началось, отменить его нельзя.",
  "Prisijunkite prie paskyros.": "Войдите в аккаунт.",
  "Pirmiausia patvirtinkite prisijungimo el. paštą.": "Сначала подтвердите адрес почты для входа.",
  "Paskyros ištrynimas suplanuotas. Naujo profilio susieti negalima.": "Удаление аккаунта запланировано. Нельзя привязать новый профиль.",
  "Paskyros susieti automatiškai nepavyko.": "Не удалось автоматически привязать аккаунт.",
  "Paskyros susieti nepavyko. Bandykite dar kartą.": "Не удалось привязать аккаунт. Повторите попытку.",
  "Patikrinkite registracijos laukus": "Проверьте поля регистрации",
  "Registracija šiuo metu nepasiekiama. Bandykite vėliau.": "Регистрация сейчас недоступна. Повторите попытку позже.",
  "Norėdami registruotis, pirmiausia prisijunkite.": "Чтобы зарегистрироваться, сначала войдите.",
  "Paskyros ištrynimas suplanuotas. Naujo profilio kurti negalima.": "Удаление аккаунта запланировано. Нельзя создать новый профиль.",
  "Viešai vietovei nurodykite miestą ar gyvenvietę, ne gatvę ar adresą.": "Для публичного местоположения укажите город или населённый пункт, а не улицу или адрес.",
  "Specialisto profilio sukurti nepavyko. Bandykite dar kartą.": "Не удалось создать профиль специалиста. Повторите попытку.",
  "Darbo sričių išsaugoti nepavyko. Bandykite dar kartą.": "Не удалось сохранить направления работы. Повторите попытку.",
  "Paslaugų išsaugoti nepavyko. Bandykite dar kartą.": "Не удалось сохранить услуги. Повторите попытку.",
  "Paslaugų kainų išsaugoti nepavyko. Bandykite dar kartą.": "Не удалось сохранить цены услуг. Повторите попытку.",
  "Darbo vietovės išsaugoti nepavyko. Bandykite dar kartą.": "Не удалось сохранить рабочее местоположение. Повторите попытку.",
  "Nuotraukų duomenų išsaugoti nepavyko. Bandykite dar kartą.": "Не удалось сохранить данные фотографий. Повторите попытку.",
  "Sutikimų išsaugoti nepavyko. Bandykite dar kartą.": "Не удалось сохранить согласия. Повторите попытку.",
  "Registracijos užbaigti nepavyko. Bandykite dar kartą.": "Не удалось завершить регистрацию. Повторите попытку.",
  "Pasirinkite adresą iš sąrašo arba įrašykite jį ranka.": "Выберите адрес из списка или введите вручную.",
  "Nuotraukų apdoroti nepavyko.": "Не удалось обработать фотографии.",
  "Failas nerastas.": "Файл не найден.",
  "Įkelti nepavyko.": "Не удалось загрузить.",
  "Patvirtinti nepavyko.": "Не удалось подтвердить.",
  "Pasirinkite pakaitinę nuotrauką. Dabartinė liks vieša iki patvirtinimo.": "Выберите новую фотографию. Текущая останется публичной до подтверждения.",
  "Prašymo pateikti nepavyko.": "Не удалось отправить запрос.",
  "Paskyros ištrynimo suplanuoti nepavyko.": "Не удалось запланировать удаление аккаунта.",
  "Paskyros ištrynimo atšaukti nepavyko.": "Не удалось отменить удаление аккаунта.",
  "Darbų nuotrauka": "Фотография работы"
});

const patterns: Array<[RegExp, (match: RegExpMatchArray) => string]> = [
  [/^(\d+) iš (\d+) nuotraukų$/, (m) => `${m[1]} из ${m[2]} фотографий`],
  [/^Įkelti (\d*) nuotr\.$/, (m) => `Загрузить ${m[1]} фото`],
  [/^(\d+) nuotraukos optimizuotos ir paruoštos peržiūrai\.$/, (m) => `${m[1]} фотографий обработано и готово к просмотру.`],
  [/^(\d+) nuotr\.$/, (m) => `${m[1]} фото`],
  [/^apie (\d+(?:[.,]\d+)?) km$/, (m) => `около ${m[1]} км`],
  [/^(\d+) km spindulys$/, (m) => `радиус ${m[1]} км`],
  [/^nuo €(\d+)\/val\.$/, (m) => `от ${m[1]} €/ч`],
  [/^Pasiekėte (\d+) paslaugų limitą\.$/, (m) => `Достигнут лимит в ${m[1]} услуг.`],
  [/^Pasiekėte (\d+) darbo sričių limitą\.$/, (m) => `Достигнут лимит в ${m[1]} направлений.`],
  [/^Nustatyta (\d+) paslaugų$/, (m) => `Выбрано услуг: ${m[1]}`],
  [/^Nepavyko įkelti: (.+)\.$/, (m) => `Не удалось загрузить: ${m[1]}.`],
  [/^Iki (\d+) nuotraukų\. JPG, PNG, WebP arba HEIC iki 10 MB automatiškai sumažinamos iki 1920 px ir 1 MB WebP\. Originalai nesaugomi\.$/, (m) => `До ${m[1]} фотографий. JPG, PNG, WebP или HEIC до 10 МБ автоматически уменьшаются до 1920 пикселей и 1 МБ WebP. Оригиналы не сохраняются.`],
  [/^(\d+) iš (\d+) nuotraukų pasirinktos$/, (m) => `Выбрано ${m[1]} из ${m[2]} фотографий`],
  [/^Iki (\d+) km$/, (m) => `До ${m[1]} км`],
  [/^Pasirinkite kainą nuo (\d+) iki (\d+) €\.$/, (m) => `Выберите цену от ${m[1]} до ${m[2]} €.`],
  [/^Darbo sritys: pasirinkta (\d+) iš (\d+) · liko (\d+)$/, (m) => `Направления: выбрано ${m[1]} из ${m[2]} · осталось ${m[3]}`],
  [/^Paslaugos: pasirinkta (\d+) iš (\d+) · liko (\d+)$/, (m) => `Услуги: выбрано ${m[1]} из ${m[2]} · осталось ${m[3]}`],
  [/^Trumpas aprašymas \* \((\d+) ženklų; mažiausiai 80\)$/, (m) => `Краткое описание * (${m[1]} символов; минимум 80)`],
  [/^Registracijos numeris: (.+)$/, (m) => `Номер регистрации: ${m[1]}`],
  [/^Nuotraukos URL (\d+)$/, (m) => `URL фотографии ${m[1]}`],
  [/^(.+) kaina už m²$/, (m) => `${m[1]}: цена за м²`],
  [/^Jūsų profilis paslėptas\. Paskyra bus visam laikui ištrinta (.+)\. Iki tos dienos ištrynimą galite atšaukti\.$/, (m) => `Ваш профиль скрыт. Аккаунт будет удалён навсегда ${m[1]}. До этой даты удаление можно отменить.`]
];

export function translateTradespersonText(value: string): string {
  const trimmed = value.trim();
  if (!trimmed) return value;
  let translated = russianCopy[trimmed];
  if (!translated) {
    for (const [pattern, replacement] of patterns) {
      const match = trimmed.match(pattern);
      if (match) { translated = replacement(match); break; }
    }
  }
  if (!translated) return value;
  const leading = value.match(/^\s*/)?.[0] ?? "";
  const trailing = value.match(/\s*$/)?.[0] ?? "";
  return `${leading}${translated}${trailing}`;
}
