with categories(name, slug, sort_order) as (
  values
    ('Vidaus apdaila', 'vidaus-apdaila', 1),
    ('Santechnika', 'santechnika', 2),
    ('Elektra ir apsaugos sistemos', 'elektra-ir-apsauga', 3),
    ('Šildymas, vėdinimas ir kondicionavimas', 'sildymas-vedinimas-kondicionavimas', 4),
    ('Stogai ir skardinimas', 'stogai-ir-skardinimas', 5),
    ('Fasadai ir šiltinimas', 'fasadai-ir-siltinimas', 6),
    ('Statyba ir konstrukcijos', 'statyba-ir-konstrukcijos', 7),
    ('Langai, durys ir laiptai', 'langai-durys-laiptai', 8),
    ('Medžio darbai ir baldai', 'medzio-darbai-ir-baldai', 9),
    ('Lauko ir sklypo darbai', 'lauko-ir-sklypo-darbai', 10),
    ('Griovimas ir atliekų išvežimas', 'griovimas-ir-atlieku-isvezimas', 11),
    ('Meistras į namus', 'meistras-i-namus', 12),
    ('Projektavimas ir darbų priežiūra', 'projektavimas-ir-prieziura', 13)
)
insert into service_categories(name, slug, sort_order, is_active)
select name, slug, sort_order, true from categories
on conflict (slug) do update set name = excluded.name, sort_order = excluded.sort_order, is_active = true;

with services(category_slug, name, slug) as (
  values
    ('vidaus-apdaila','Plytelių klijavimas','plyteliu-klijavimas'),
    ('vidaus-apdaila','Vonios kambario įrengimas','vonios-kambario-irengimas'),
    ('vidaus-apdaila','Glaistymas','glaistymas'),
    ('vidaus-apdaila','Dažymas','dazymas'),
    ('vidaus-apdaila','Tapetavimas','tapetavimas'),
    ('vidaus-apdaila','Gipso kartono montavimas','gipso-kartono-montavimas'),
    ('vidaus-apdaila','Pertvarų montavimas','pertvaru-montavimas'),
    ('vidaus-apdaila','Pakabinamų lubų montavimas','pakabinamu-lubu-montavimas'),
    ('vidaus-apdaila','Laminato klojimas','laminato-klojimas'),
    ('vidaus-apdaila','Parketo ir medinių grindų darbai','parketo-ir-mediniu-grindu-darbai'),
    ('vidaus-apdaila','Grindjuosčių montavimas','grindjuosciu-montavimas'),
    ('vidaus-apdaila','Vidaus durų montavimas','vidaus-duru-montavimas'),
    ('vidaus-apdaila','Pilna buto apdaila','pilna-buto-apdaila'),
    ('vidaus-apdaila','Remonto darbai','remonto-darbai'),
    ('santechnika','Vandentiekio vamzdynai','vandentiekio-vamzdynai'),
    ('santechnika','Nuotekų vamzdynai','nuoteku-vamzdynai'),
    ('santechnika','Santechnikos remontas','santechnikos-remontas'),
    ('santechnika','Unitazų montavimas','unitazu-montavimas'),
    ('santechnika','Praustuvų montavimas','praustuvu-montavimas'),
    ('santechnika','Maišytuvų montavimas','maisytuvu-montavimas'),
    ('santechnika','Vonių montavimas','voniu-montavimas'),
    ('santechnika','Dušo kabinų montavimas','duso-kabinu-montavimas'),
    ('santechnika','Boilerio montavimas','boilerio-montavimas'),
    ('santechnika','Vandens filtrų montavimas','vandens-filtru-montavimas'),
    ('santechnika','Trapų ir nuotekų pajungimas','trapu-ir-nuoteku-pajungimas'),
    ('santechnika','Avarinė santechnika','avarine-santechnika'),
    ('elektra-ir-apsauga','Elektros instaliacija','elektros-instaliacija'),
    ('elektra-ir-apsauga','Elektros instaliacijos remontas','elektros-instaliacijos-remontas'),
    ('elektra-ir-apsauga','Rozečių montavimas','rozeciu-montavimas'),
    ('elektra-ir-apsauga','Jungiklių montavimas','jungikliu-montavimas'),
    ('elektra-ir-apsauga','Šviestuvų montavimas','sviestuvu-montavimas'),
    ('elektra-ir-apsauga','Elektros skydelio darbai','elektros-skydelio-darbai'),
    ('elektra-ir-apsauga','Gedimų paieška','gedimu-paieska'),
    ('elektra-ir-apsauga','Lauko apšvietimas','lauko-apsvietimas'),
    ('elektra-ir-apsauga','Signalizacijos','signalizacijos'),
    ('elektra-ir-apsauga','Vaizdo stebėjimo kameros','vaizdo-stebejimo-kameros'),
    ('elektra-ir-apsauga','Domofonai','domofonai'),
    ('elektra-ir-apsauga','Elektromobilių įkrovimo stotelės','elektromobiliu-ikrovimo-stoteles'),
    ('sildymas-vedinimas-kondicionavimas','Katilų montavimas','katilu-montavimas'),
    ('sildymas-vedinimas-kondicionavimas','Katilų remontas','katilu-remontas'),
    ('sildymas-vedinimas-kondicionavimas','Šilumos siurblių montavimas','silumos-siurbliu-montavimas'),
    ('sildymas-vedinimas-kondicionavimas','Grindinis šildymas','grindinis-sildymas'),
    ('sildymas-vedinimas-kondicionavimas','Radiatorių montavimas','radiatoriu-montavimas'),
    ('sildymas-vedinimas-kondicionavimas','Rekuperacijos sistemos','rekuperacijos-sistemos'),
    ('sildymas-vedinimas-kondicionavimas','Vėdinimo sistemos','vedinimo-sistemos'),
    ('sildymas-vedinimas-kondicionavimas','Kondicionierių montavimas','kondicionieriu-montavimas'),
    ('sildymas-vedinimas-kondicionavimas','Kondicionierių priežiūra','kondicionieriu-prieziura'),
    ('sildymas-vedinimas-kondicionavimas','Kaminų montavimas','kaminu-montavimas'),
    ('sildymas-vedinimas-kondicionavimas','Kaminų valymas','kaminu-valymas'),
    ('stogai-ir-skardinimas','Naujo stogo įrengimas','naujo-stogo-irengimas'),
    ('stogai-ir-skardinimas','Stogo remontas','stogo-remontas'),
    ('stogai-ir-skardinimas','Stogo šiltinimas','stogo-siltinimas'),
    ('stogai-ir-skardinimas','Stogo dangos keitimas','stogo-dangos-keitimas'),
    ('stogai-ir-skardinimas','Skardinimo darbai','skardinimo-darbai'),
    ('stogai-ir-skardinimas','Lietaus nuvedimo sistemos','lietaus-nuvedimo-sistemos'),
    ('stogai-ir-skardinimas','Kaminų skardinimas','kaminu-skardinimas'),
    ('stogai-ir-skardinimas','Stoglangių montavimas','stoglangiu-montavimas'),
    ('stogai-ir-skardinimas','Sniego užtvarų montavimas','sniego-uztvaru-montavimas'),
    ('fasadai-ir-siltinimas','Fasado šiltinimas','fasado-siltinimas'),
    ('fasadai-ir-siltinimas','Fasado tinkavimas','fasado-tinkavimas'),
    ('fasadai-ir-siltinimas','Fasado dažymas','fasado-dazymas'),
    ('fasadai-ir-siltinimas','Ventiliuojami fasadai','ventiliuojami-fasadai'),
    ('fasadai-ir-siltinimas','Cokolio apdaila','cokolio-apdaila'),
    ('fasadai-ir-siltinimas','Angokraščių apdaila','angokrasciu-apdaila'),
    ('fasadai-ir-siltinimas','Lauko sienų remontas','lauko-sienu-remontas'),
    ('fasadai-ir-siltinimas','Pastatų sandarinimas','pastatu-sandarinimas'),
    ('statyba-ir-konstrukcijos','Individualių namų statyba','individualiu-namu-statyba'),
    ('statyba-ir-konstrukcijos','Karkasinių namų statyba','karkasiniu-namu-statyba'),
    ('statyba-ir-konstrukcijos','Mūro darbai','muro-darbai'),
    ('statyba-ir-konstrukcijos','Pamatų įrengimas','pamatu-irengimas'),
    ('statyba-ir-konstrukcijos','Betonavimas','betonavimas'),
    ('statyba-ir-konstrukcijos','Perdangų įrengimas','perdangu-irengimas'),
    ('statyba-ir-konstrukcijos','Priestatų statyba','priestatu-statyba'),
    ('statyba-ir-konstrukcijos','Stoginių statyba','stoginiu-statyba'),
    ('statyba-ir-konstrukcijos','Angų įrengimas','angu-irengimas'),
    ('statyba-ir-konstrukcijos','Metalo konstrukcijos','metalo-konstrukcijos')
)
insert into service_subcategories(service_category_id, name, slug, is_active)
select category.id, services.name, services.slug, true
from services join service_categories category on category.slug = services.category_slug
on conflict (slug) do update set service_category_id = excluded.service_category_id, name = excluded.name, is_active = true;
