-- Cover every Lithuanian municipality, plus Varėna town. Existing town IDs are
-- retained so previously imported jobs and links keep their meaning.
-- Municipality names follow the national list; a collector must still verify
-- which municipality contains a town before using a broader area ID.
insert into public.job_areas (id, name, kind, aliases) values
  ('akmenes-rajonas', 'Akmenės rajonas', 'municipality', array['Akmenės r.']),
  ('alytus', 'Alytus', 'town', array['Alytuje']),
  ('alytaus-rajonas', 'Alytaus rajonas', 'municipality', array['Alytaus r.']),
  ('anyksciu-rajonas', 'Anykščių rajonas', 'municipality', array['Anykščių r.']),
  ('birstono-savivaldybe', 'Birštono savivaldybė', 'municipality', array['Birštonas']),
  ('birzu-rajonas', 'Biržų rajonas', 'municipality', array['Biržų r.']),
  ('druskininku-savivaldybe', 'Druskininkų savivaldybė', 'municipality', array['Druskininkai']),
  ('elektrenu-savivaldybe', 'Elektrėnų savivaldybė', 'municipality', array['Elektrėnai']),
  ('ignalinos-rajonas', 'Ignalinos rajonas', 'municipality', array['Ignalinos r.']),
  ('jonavos-rajonas', 'Jonavos rajonas', 'municipality', array['Jonavos r.']),
  ('joniskio-rajonas', 'Joniškio rajonas', 'municipality', array['Joniškio r.']),
  ('jurbarko-rajonas', 'Jurbarko rajonas', 'municipality', array['Jurbarko r.']),
  ('kaisiadoriu-rajonas', 'Kaišiadorių rajonas', 'municipality', array['Kaišiadorių r.']),
  ('kalvarijos-savivaldybe', 'Kalvarijos savivaldybė', 'municipality', array['Kalvarija']),
  ('kaunas', 'Kaunas', 'town', array['Kaune']),
  ('kauno-rajonas', 'Kauno rajonas', 'municipality', array['Kauno r.']),
  ('kazlu-rudos-savivaldybe', 'Kazlų Rūdos savivaldybė', 'municipality', array['Kazlų Rūda']),
  ('kedainiu-rajonas', 'Kėdainių rajonas', 'municipality', array['Kėdainių r.']),
  ('kelmes-rajonas', 'Kelmės rajonas', 'municipality', array['Kelmės r.']),
  ('klaipeda', 'Klaipėda', 'town', array['Klaipėdoje']),
  ('klaipedos-rajonas', 'Klaipėdos rajonas', 'municipality', array['Klaipėdos r.']),
  ('kretingos-rajonas', 'Kretingos rajonas', 'municipality', array['Kretingos r.']),
  ('kupiskio-rajonas', 'Kupiškio rajonas', 'municipality', array['Kupiškio r.']),
  ('lazdiju-rajonas', 'Lazdijų rajonas', 'municipality', array['Lazdijų r.']),
  ('marijampoles-savivaldybe', 'Marijampolės savivaldybė', 'municipality', array['Marijampolės sav.']),
  ('mazeikiu-rajonas', 'Mažeikių rajonas', 'municipality', array['Mažeikių r.']),
  ('moletu-rajonas', 'Molėtų rajonas', 'municipality', array['Molėtų r.']),
  ('neringos-savivaldybe', 'Neringos savivaldybė', 'municipality', array['Neringa']),
  ('pagegiu-savivaldybe', 'Pagėgių savivaldybė', 'municipality', array['Pagėgiai']),
  ('pakruojo-rajonas', 'Pakruojo rajonas', 'municipality', array['Pakruojo r.']),
  ('palanga', 'Palanga', 'town', array['Palangoje']),
  ('panevezys', 'Panevėžys', 'town', array['Panevėžyje']),
  ('panevezio-rajonas', 'Panevėžio rajonas', 'municipality', array['Panevėžio r.']),
  ('pasvalio-rajonas', 'Pasvalio rajonas', 'municipality', array['Pasvalio r.']),
  ('plunges-rajonas', 'Plungės rajonas', 'municipality', array['Plungės r.']),
  ('prienu-rajonas', 'Prienų rajonas', 'municipality', array['Prienų r.']),
  ('radviliskio-rajonas', 'Radviliškio rajonas', 'municipality', array['Radviliškio r.']),
  ('raseiniu-rajonas', 'Raseinių rajonas', 'municipality', array['Raseinių r.']),
  ('rietavo-savivaldybe', 'Rietavo savivaldybė', 'municipality', array['Rietavas']),
  ('rokiskio-rajonas', 'Rokiškio rajonas', 'municipality', array['Rokiškio r.']),
  ('skuodo-rajonas', 'Skuodo rajonas', 'municipality', array['Skuodo r.']),
  ('sakiu-rajonas', 'Šakių rajonas', 'municipality', array['Šakių r.']),
  ('salcininku-rajonas', 'Šalčininkų rajonas', 'municipality', array['Šalčininkų r.']),
  ('siauliai', 'Šiauliai', 'town', array['Šiauliuose']),
  ('siauliu-rajonas', 'Šiaulių rajonas', 'municipality', array['Šiaulių r.']),
  ('silales-rajonas', 'Šilalės rajonas', 'municipality', array['Šilalės r.']),
  ('silutes-rajonas', 'Šilutės rajonas', 'municipality', array['Šilutės r.']),
  ('sirvintu-rajonas', 'Širvintų rajonas', 'municipality', array['Širvintų r.']),
  ('svencioniu-rajonas', 'Švenčionių rajonas', 'municipality', array['Švenčionių r.']),
  ('taurages-rajonas', 'Tauragės rajonas', 'municipality', array['Tauragės r.']),
  ('telsiu-rajonas', 'Telšių rajonas', 'municipality', array['Telšių r.']),
  ('traku-rajonas', 'Trakų rajonas', 'municipality', array['Trakų r.']),
  ('ukmerges-rajonas', 'Ukmergės rajonas', 'municipality', array['Ukmergės r.']),
  ('utenos-rajonas', 'Utenos rajonas', 'municipality', array['Utenos r.']),
  ('varenos-rajonas', 'Varėnos rajonas', 'municipality', array['Varėnos r.']),
  ('vilkaviskio-rajonas', 'Vilkaviškio rajonas', 'municipality', array['Vilkaviškio r.']),
  ('vilnius', 'Vilnius', 'town', array['Vilniuje']),
  ('vilniaus-rajonas', 'Vilniaus rajonas', 'municipality', array['Vilniaus r.']),
  ('visagino-savivaldybe', 'Visagino savivaldybė', 'municipality', array['Visaginas']),
  ('zarasu-rajonas', 'Zarasų rajonas', 'municipality', array['Zarasų r.']),
  ('varena', 'Varėna', 'town', array['Varėnoje'])
on conflict (id) do nothing;
