export const validRegistration = {
  name: "Test Meistras",
  phone: "+37061234567",
  email: "test@example.lt",
  address: "Gedimino pr. 1, Vilnius, Lithuania",
  placeId: "test-place-id",
  latitude: 54.6872,
  longitude: 25.2797,
  town: "Vilnius",
  street: "Gedimino pr.",
  postcode: "01103",
  trade: "Apdaila",
  categorySlugs: ["apdaila"],
  subcategorySlugs: ["dazymas"],
  description: "Testinis meistro profilio aprasymas validacijai.",
  travelRange: "25",
  photoUrls: [],
  photoUploads: [],
  consentAccepted: true,
  termsAccepted: true,
  privacyAcknowledged: true,
  publicContactConsent: true
};

export const baseProfile = {
  id: "consented-public",
  display_name: "Consented Public",
  company_name: null,
  phone: "+37061234567",
  whatsapp_number: null,
  email: "public@localpro.lt",
  base_city: "Vilnius",
  radius_km: 25,
  latitude: 54.6872,
  longitude: 25.2797,
  description: "Pakankamai ilgas aprasymas viesam specialistu profilio testui.",
  review_score: null,
  review_count: null,
  verification_labels: [],
  public_status: "public",
  approval_status: "approved",
  is_demo: false,
  public_contact_consent_at: "2026-07-16T05:00:00.000Z",
  source: "self-registration",
  service_area_label: null,
  service_categories: { name: "Apdaila", slug: "apdaila" },
  profile_services: [],
  operating_areas: [{ city: "Vilnius", radius_km: 25 }],
  profile_photos: [
    { id: "approved-photo", label: "Approved", url: "https://example.lt/approved.jpg", moderation_status: "approved", sort_order: 1, removed_from_profile_at: null },
    { id: "pending-photo", label: "Pending", url: "https://example.lt/pending.jpg", moderation_status: "pending", sort_order: 2, removed_from_profile_at: null },
    { id: "rejected-photo", label: "Rejected", url: "https://example.lt/rejected.jpg", moderation_status: "rejected", sort_order: 3, removed_from_profile_at: null }
  ],
  reviews: []
};
